version: "3.8"
services:
  project:
    build:
      context: .
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    stdin_open: true
    tty: true
    volumes:
      - .:/home/user/project
