name: placeholder-project-name
services:
  main:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    hostname: placeholder-project-name
    stdin_open: true
    tty: true
    volumes:
      - ..:/home/user/workspace
